name: GIT CI/CD to AWS
on:
  push:
    branches:
      - main
env:
  PROJECT_NAME: gitAndCICD
jobs:
  prep-docker:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut ci
        uses: actions/checkout@v2
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
