name: GIT CI/CD to AWS
on:
  push:
    branches:
      - main
env:
  PROJECT_NAME: gitAndCICD
jobs:
  prep-docker:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut ci
        uses: actions/checkout@v2
      - name: Output Run ID
        run: echo run id is ${{ github.run_id }}
      - name: Output Run Number
        run: echo run number is ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo run_attempt is ${{ github.run_attempt }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: check docker version
        run: echo docker --version